name = "zcg-chat"
main = "src/index.js"
compatibility_date = "2026-08-01"

[vars]
ALLOWED_ORIGINS = "https://www.zaidiconsultinggroup.com,https://zaidiconsultinggroup.com,https://zcgllc.github.io,http://localhost:8080,http://127.0.0.1:8080"
